server:
  port: 8080
spring:
  application:
    name: astock
  elasticsearch:
    rest:
      uris: http://localhost:9200
      username:
      password:
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-bean-definition-overriding: true
